[storage]
driver = "overlay"

[storage.options]
# Forcing fuse-overlayfs to saturate NVMe IOPS and avoid vfs fallback
mount_program = "/usr/bin/fuse-overlayfs"

[storage.options.overlay]
mountopt = "nodev,metacopy=on"
