[package]
name = "bound-system"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "process", "fs", "sync", "signal", "io-util"] }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
which = "6"
libc = "0.2"
rlimit = "0.10"
nix = "0.27"
