//! Bus event types — defines all events flowing through the system.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Kinds of events flowing through the bus.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum BusEventKind {
    /// A query was received (from gateway, API, etc.)
    QueryReceived,
    /// A response was generated by the LLM.
    ResponseGenerated,
    /// Semantic evaluation completed (from soullink-eval).
    EvaluationCompleted,
    /// A concept was created or updated in MemoryGraph.
    ConceptUpdated,
    /// An edge weight was adjusted.
    EdgeWeightAdjusted,
    /// A tool action was executed.
    ActionExecuted,
    /// Senate deliberation completed.
    SenateCompleted,
    /// Reasoning tree node evaluated.
    ReasoningEvaluated,
    /// Proactive random walk discovered a connection.
    RandomWalkDiscovery,
    /// System health / heartbeat.
    Heartbeat,
}

/// An event on the bus.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BusEvent {
    /// Unique event ID.
    pub id: String,
    /// Kind of event.
    pub kind: BusEventKind,
    /// Source module that emitted the event.
    pub source: String,
    /// JSON payload — varies by kind.
    pub payload: serde_json::Value,
    /// Timestamp.
    pub timestamp: DateTime<Utc>,
}

impl BusEvent {
    pub fn new(kind: BusEventKind, source: impl Into<String>, payload: serde_json::Value) -> Self {
        Self {
            id: format!(
                "{:x}",
                chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0)
            ),
            kind,
            source: source.into(),
            payload,
            timestamp: Utc::now(),
        }
    }

    /// Convenience: create event with empty payload.
    pub fn empty(kind: BusEventKind, source: impl Into<String>) -> Self {
        Self::new(kind, source, serde_json::Value::Null)
    }
}
