#![forbid(unsafe_code)]
#![deny(clippy::todo, clippy::unimplemented)]
#![allow(
    clippy::module_name_repetitions,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::doc_markdown,
    clippy::must_use_candidate,
    clippy::missing_const_for_fn,
    clippy::too_many_lines,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_possible_wrap,
    clippy::cast_precision_loss,
    clippy::unnecessary_cast
)]

//! avid-critic — Auto-reviewer for AVID.
//!
//! Reads code generated by `avid-mimic`, validates it with an AST pass,
//! rejects or requests repair, runs the candidate in `avid-sandbox`, and
//! returns a quality score.
//!
//! Loop: **mimic → critic → repair → sandbox → score**.

use std::sync::Arc;
use std::time::Duration;
use tracing::{info, warn};

use avid_core::llm::{ChatBackend, LlmError};
use avid_mimic::CloneOutput;
use avid_sandbox::{ExecutionResult, Sandbox};

// ── Errors ──────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum CriticError {
    #[error("syntax errors: {0:?}")]
    Syntax(Vec<String>),

    #[error("sandbox error: {0}")]
    Sandbox(String),

    #[error("LLM error: {0}")]
    Llm(#[from] LlmError),

    #[error("repair exhausted after {0} attempts")]
    RepairExhausted(u32),
}

// ── Result ─────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct CriticResult {
    pub passed_syntax: bool,
    pub passed_sandbox: bool,
    pub repair_attempts: u32,
    pub sandbox_output: ExecutionResult,
    pub score: f64,
}

// ── Syntax validator ────────────────────────────────────────

pub fn validate_syntax(output: &CloneOutput) -> Result<(), Vec<String>> {
    let mut errors = Vec::new();
    for (path, content) in &output.files {
        if !std::path::Path::new(path)
            .extension()
            .is_some_and(|ext| ext.eq_ignore_ascii_case("py"))
        {
            continue;
        }
        if let Err(e) =
            rustpython_parser::parse(content, rustpython_parser::Mode::Module, "<generated>")
        {
            errors.push(format!("{path}: {e}"));
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

// ── Repair helper ───────────────────────────────────────────

async fn repair_with_llm(
    llm: &dyn ChatBackend,
    code: &str,
    language: &str,
    error_msg: &str,
) -> Result<String, LlmError> {
    let system = format!(
        "You are a strict {language} compiler. Fix the syntax error and return ONLY the corrected code, no explanation."
    );
    let user = format!(
        "The following {language} code has a syntax error:\n```\n{code}\n```\nError: {error_msg}\n\nReturn only corrected code."
    );
    llm.chat(&system, &user, false, Duration::from_secs(60))
        .await
}

// ── CriticEngine ──────────────────────────────────────────

pub struct CriticEngine {
    llm: Option<Arc<dyn ChatBackend>>,
    sandbox: Sandbox,
    max_repair_attempts: u32,
}

impl CriticEngine {
    pub fn new(
        llm: Option<Arc<dyn ChatBackend>>,
        sandbox: Sandbox,
        max_repair_attempts: u32,
    ) -> Self {
        Self {
            llm,
            sandbox,
            max_repair_attempts,
        }
    }

    /// Full review pipeline.
    ///
    /// 1. Validate syntax.
    /// 2. If errors → try LLM repair up to `max_repair_attempts`.
    /// 3. Run in sandbox.
    /// 4. Return score.
    #[allow(clippy::cognitive_complexity)]
    pub async fn review(&self, output: &CloneOutput) -> Result<CriticResult, CriticError> {
        let mut current = output.clone();
        let mut repair_attempts = 0u32;

        // Step 1 — syntax
        let mut syntax_errors = validate_syntax(&current).err();

        // Step 2 — repair loop
        while let Some(ref errs) = syntax_errors {
            if repair_attempts >= self.max_repair_attempts {
                return Err(CriticError::RepairExhausted(repair_attempts));
            }
            repair_attempts += 1;
            warn!(
                attempt = repair_attempts,
                "Syntax errors detected, attempting repair"
            );

            let Some(ref llm) = self.llm else {
                return Err(CriticError::Syntax(errs.clone()));
            };

            let error_summary = errs.join("\n");
            let entrypoint_content = current
                .files
                .get(&current.entrypoint)
                .cloned()
                .unwrap_or_default();

            match repair_with_llm(
                llm.as_ref(),
                &entrypoint_content,
                &current.language,
                &error_summary,
            )
            .await
            {
                Ok(fixed) => {
                    // Replace entrypoint with fixed code
                    let mut next = current.clone();
                    next.files.insert(next.entrypoint.clone(), fixed);
                    current = next;
                    syntax_errors = validate_syntax(&current).err();
                    if syntax_errors.is_none() {
                        info!(attempt = repair_attempts, "Repair succeeded");
                    }
                }
                Err(e) => {
                    warn!(attempt = repair_attempts, error = %e, "Repair attempt failed");
                    break;
                }
            }
        }

        if let Some(errs) = syntax_errors {
            return Err(CriticError::Syntax(errs));
        }

        // Step 3 — sandbox
        let sandbox_result = self
            .sandbox
            .run(&current.files, &current.entrypoint)
            .await
            .map_err(|e| CriticError::Sandbox(e.to_string()))?;

        let passed_sandbox = sandbox_result.status == avid_sandbox::ExecStatus::Success;

        // Step 4 — score
        let score = if passed_sandbox { 1.0 } else { 0.0 };

        Ok(CriticResult {
            passed_syntax: true,
            passed_sandbox,
            repair_attempts,
            sandbox_output: sandbox_result,
            score,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn test_validate_syntax_ok() {
        let output = CloneOutput {
            language: "python".into(),
            files: HashMap::from([("main.py".into(), "print(42)\n".into())]),
            entrypoint: "main.py".into(),
        };
        assert!(validate_syntax(&output).is_ok());
    }

    #[test]
    fn test_validate_syntax_bad() {
        let output = CloneOutput {
            language: "python".into(),
            files: HashMap::from([("main.py".into(), "print(42\n".into())]),
            entrypoint: "main.py".into(),
        };
        let errs = validate_syntax(&output).unwrap_err();
        assert!(!errs.is_empty());
    }
}
