[package]
name = "scirust-gpu"
version = "0.6.0"
edition = "2021"

[dependencies]
rayon = { version = "1.10", optional = true }
wgpu = { version = "0.20", optional = true }
pollster = { version = "0.3", optional = true }
bytemuck = { version = "1.16", optional = true }
half = "2.5"
scirust-core = { path = "../scirust-core", optional = true }
libc = "0.2"

[features]
default = ["cpu-fallback"]
cpu-fallback = ["rayon"]
cuda = []
gpu-cuda = ["cuda"]
gpu-uma = ["gpu-cuda"]
wgpu = ["dep:wgpu", "dep:pollster", "dep:bytemuck", "dep:scirust-core"]
