//! SciRust Trading Pipeline — News → Enrichment → Decision.
//!
//! Connects the news enrichment engine to the decision engine,
//! forming a complete pipeline from raw events to trade signals.

use scirust_trading_core::{
    Category, CodifiedEvent, EnrichmentLevel, EventTiming, MarketReaction, MarketState, Polarity,
    Reliability, Side, Symbol, Target,
};
use serde::{Deserialize, Serialize};

// ── Decision Types ──────────────────────────────────────────────────────

/// A trading decision generated by the pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Decision {
    pub id: uuid::Uuid,
    pub event_id: uuid::Uuid,
    pub action: DecisionAction,
    pub symbol: Symbol,
    pub confidence: f64,
    pub score: f64,
    pub reasoning: String,
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

/// The action to take.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DecisionAction {
    Buy,
    Sell,
    Hold,
    Skip,
}

/// Configuration for the pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineConfig {
    /// Minimum score to generate a Buy/Sell decision.
    pub min_score: f64,
    /// Minimum confidence to act.
    pub min_confidence: f64,
    /// Maximum age of events to consider (hours).
    pub max_age_hours: i64,
    /// Default symbol for decisions.
    pub default_symbol: Symbol,
}

impl Default for PipelineConfig {
    fn default() -> Self {
        Self {
            min_score: 0.3,
            min_confidence: 0.5,
            max_age_hours: 24,
            default_symbol: Symbol::new("BTC", "USDT"),
        }
    }
}

// ── Pipeline ────────────────────────────────────────────────────────────

/// The trading pipeline processes events into decisions.
pub struct TradingPipeline {
    config: PipelineConfig,
    /// Processed event IDs (dedup).
    processed: std::collections::HashSet<uuid::Uuid>,
}

impl TradingPipeline {
    pub fn new(config: PipelineConfig) -> Self {
        Self {
            config,
            processed: std::collections::HashSet::new(),
        }
    }

    pub fn default() -> Self {
        Self::new(PipelineConfig::default())
    }

    /// Process a single enriched event into a decision.
    pub fn process_event(
        &mut self,
        event: &CodifiedEvent,
        market: Option<&MarketState>,
    ) -> Option<Decision> {
        // Dedup
        if self.processed.contains(&event.id) {
            return None;
        }
        self.processed.insert(event.id);

        // Age check
        let age_hours = (chrono::Utc::now() - event.detected_at).num_hours();
        if age_hours > self.config.max_age_hours {
            tracing::debug!(event_id = %event.id, age_hours, "event too old, skipping");
            return None;
        }

        // Compute score
        let score = event.weighted_score(chrono::Utc::now());

        // Compute confidence from available signals
        let confidence = self.compute_confidence(event, market);

        // Determine action
        let action = self.determine_action(score, confidence);

        // Generate reasoning
        let reasoning = self.generate_reasoning(event, score, confidence, action);

        if action == DecisionAction::Skip {
            return None;
        }

        let symbol = market
            .map(|m| m.symbol.clone())
            .unwrap_or_else(|| self.config.default_symbol.clone());

        Some(Decision {
            id: uuid::Uuid::new_v4(),
            event_id: event.id,
            action,
            symbol,
            confidence,
            score,
            reasoning,
            timestamp: chrono::Utc::now(),
        })
    }

    /// Process a batch of events.
    pub fn process_batch(
        &mut self,
        events: &[CodifiedEvent],
        market: Option<&MarketState>,
    ) -> Vec<Decision> {
        events
            .iter()
            .filter_map(|e| self.process_event(e, market))
            .collect()
    }

    fn compute_confidence(&self, event: &CodifiedEvent, market: Option<&MarketState>) -> f64 {
        let mut signals = Vec::new();

        // Signal 1: Source reliability
        signals.push(event.source_reliability.value());

        // Signal 2: Semantic confidence
        if let Some(conf) = event.semantic_confidence {
            signals.push(conf);
        }

        // Signal 3: Historical response confidence
        if let Some(ref reaction) = event.historical_response {
            signals.push(reaction.confidence);
        }

        // Signal 4: Market microstructure
        if let Some(m) = market {
            // Lower spread = higher confidence
            let spread_score = (1.0 - (m.spread_bps / 10.0).min(1.0)).max(0.0);
            signals.push(spread_score);

            // Higher volume = higher confidence
            let vol_score = (m.volume_1min / 20.0).min(1.0);
            signals.push(vol_score);
        }

        if signals.is_empty() {
            0.3
        } else {
            signals.iter().sum::<f64>() / signals.len() as f64
        }
    }

    fn determine_action(&self, score: f64, confidence: f64) -> DecisionAction {
        if confidence < self.config.min_confidence {
            return DecisionAction::Skip;
        }

        if score >= self.config.min_score && confidence >= self.config.min_confidence {
            DecisionAction::Buy
        } else if score <= -self.config.min_score && confidence >= self.config.min_confidence {
            DecisionAction::Sell
        } else {
            DecisionAction::Hold
        }
    }

    fn generate_reasoning(
        &self,
        event: &CodifiedEvent,
        score: f64,
        confidence: f64,
        action: DecisionAction,
    ) -> String {
        let category = format!("{:?}", event.category);
        let polarity = event
            .polarity
            .map(|p| format!("{:+.2}", p.value()))
            .unwrap_or_default();
        let magnitude = event
            .magnitude
            .map(|m| format!("{:.2}", m))
            .unwrap_or_default();

        let historical = event
            .historical_response
            .as_ref()
            .map(|r| {
                format!(
                    "historical Δ60m: {:+.1}bps (n={}, significant={})",
                    r.delta_60min_bps,
                    r.n_samples,
                    r.is_significant()
                )
            })
            .unwrap_or_default();

        format!(
            "[{:?}] score={:+.3} conf={:.3} | category={} polarity={} magnitude={} | {}",
            action, score, confidence, category, polarity, magnitude, historical
        )
    }

    /// Get the number of processed events.
    pub fn processed_count(&self) -> usize {
        self.processed.len()
    }

    /// Clear processed event cache.
    pub fn clear_cache(&mut self) {
        self.processed.clear();
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    fn make_event(score: f64) -> CodifiedEvent {
        let mut event = CodifiedEvent::builder("test", "test event")
            .category(Category::Macro)
            .timing(EventTiming::Observed(Utc::now()))
            .reliability(0.9)
            .build();
        event.polarity = Some(Polarity::new(score));
        event.magnitude = Some(0.8);
        event.semantic_confidence = Some(0.9);
        event
    }

    #[test]
    fn test_pipeline_buy_signal() {
        let mut pipeline = TradingPipeline::default();
        let event = make_event(0.5);
        let decision = pipeline.process_event(&event, None).unwrap();
        assert_eq!(decision.action, DecisionAction::Buy);
        assert!(decision.confidence > 0.5);
    }

    #[test]
    fn test_pipeline_sell_signal() {
        let mut pipeline = TradingPipeline::default();
        let event = make_event(-0.5);
        let decision = pipeline.process_event(&event, None).unwrap();
        assert_eq!(decision.action, DecisionAction::Sell);
    }

    #[test]
    fn test_pipeline_hold_neutral() {
        let mut pipeline = TradingPipeline::default();
        let event = make_event(0.1);
        let decision = pipeline.process_event(&event, None).unwrap();
        assert_eq!(decision.action, DecisionAction::Hold);
    }

    #[test]
    fn test_pipeline_dedup() {
        let mut pipeline = TradingPipeline::default();
        let event = make_event(0.5);
        let d1 = pipeline.process_event(&event, None);
        let d2 = pipeline.process_event(&event, None);
        assert!(d1.is_some());
        assert!(d2.is_none());
    }

    #[test]
    fn test_pipeline_with_market() {
        let mut pipeline = TradingPipeline::default();
        let mut event = make_event(0.5);
        // Set a very recent timestamp to minimize decay
        event.detected_at = chrono::Utc::now();
        let market = MarketState {
            exchange: scirust_trading_core::Exchange::Binance,
            symbol: Symbol::new("BTC", "USDT"),
            timestamp: Utc::now(),
            mid: 68_000.0,
            microprice: 68_001.0,
            spread_bps: 0.5,
            imbalance_5: 0.2,
            imbalance_20: 0.1,
            realized_vol_pct: 25.0,
            volume_1min: 15.0,
            flow_imbalance_1min: 0.3,
            trade_count_1min: 100,
        };
        let decision = pipeline.process_event(&event, Some(&market)).unwrap();
        assert_eq!(decision.action, DecisionAction::Buy);
        assert!(decision.confidence > 0.5);
    }

    #[test]
    fn test_pipeline_batch() {
        let mut pipeline = TradingPipeline::default();
        let events = vec![make_event(0.5), make_event(-0.5), make_event(0.1)];
        let decisions = pipeline.process_batch(&events, None);
        assert_eq!(decisions.len(), 3);
    }
}
