/// JSON + Markdown persistence for extracted facts.
///
/// Writes:
/// - `memory.db` — JSON Lines file, one fact per line
/// - `wiki/patterns.md` — Human-readable Markdown summary grouped by category
use crate::extractor::ExtractedFact;
use crate::MemoryExtractConfig;

use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use tracing::info;

/// Persist extracted facts to JSON Lines and a Markdown wiki file.
pub async fn persist_results(facts: &[ExtractedFact], config: &MemoryExtractConfig) -> Result<()> {
    persist_jsonl(facts, &config.db_path)?;
    persist_markdown(facts, &config.wiki_path)?;
    info!(
        "Persisted {} facts → {} | {}",
        facts.len(),
        config.db_path,
        config.wiki_path
    );
    Ok(())
}

/// Write facts as JSON Lines (one JSON object per line) to `path`.
fn persist_jsonl(facts: &[ExtractedFact], path: &str) -> Result<()> {
    // Ensure parent directory exists
    if let Some(parent) = Path::new(path).parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create parent dir for {:?}", parent))?;
        }
    }

    let mut out = Vec::with_capacity(facts.len());

    // Serialisable wrapper
    #[derive(serde::Serialize)]
    struct FactLine<'a> {
        category: &'a str,
        content: &'a str,
        source_file: &'a str,
        line_number: usize,
        date: Option<String>,
        confidence: f64,
    }

    for fact in facts {
        let line = FactLine {
            category: &fact.category,
            content: &fact.content,
            source_file: &fact.source_file,
            line_number: fact.line_number,
            date: fact.date.as_ref().map(|d| d.to_string()),
            confidence: fact.confidence,
        };
        let json = serde_json::to_string(&line)
            .with_context(|| format!("Failed to serialise fact: {:?}", fact))?;
        out.push(json);
    }

    let content = out.join("\n") + "\n";
    fs::write(path, &content)
        .with_context(|| format!("Failed to write JSONL to {:?}", path))?;

    info!("Wrote {} facts to {}", facts.len(), path);
    Ok(())
}

/// Write a Markdown wiki page grouped by category to `path`.
fn persist_markdown(facts: &[ExtractedFact], path: &str) -> Result<()> {
    // Ensure parent directory exists
    if let Some(parent) = Path::new(path).parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create parent dir for {:?}", parent))?;
        }
    }

    // Group by category
    let mut grouped: BTreeMap<&str, Vec<&ExtractedFact>> = BTreeMap::new();
    for fact in facts {
        grouped
            .entry(fact.category.as_str())
            .or_default()
            .push(fact);
    }

    let mut md = String::new();
    md.push_str("# Extracted Patterns & Facts\n\n");
    md.push_str(
        "_Auto-generated by `soulsystem-memory-extract`. Last updated: "
    );
    md.push_str(&chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string());
    md.push_str("_\n\n---\n\n");

    for (category, items) in &grouped {
        md.push_str(&format!("## {}\n\n", capitalize(category)));
        for fact in items {
            let date_str = fact
                .date
                .map(|d| d.to_string())
                .unwrap_or_else(|| "unknown".into());
            let confidence_str = format!("{:.0}%", fact.confidence * 100.0);
            md.push_str(&format!(
                "- {} _(confidence: {}, source: {}, line: {})_\n  - Date: {}\n",
                fact.content, confidence_str, fact.source_file, fact.line_number, date_str
            ));
        }
        md.push('\n');
    }

    // Summary footer
    md.push_str("---\n\n");
    md.push_str(&format!(
        "_{} total facts extracted._\n",
        facts.len()
    ));

    fs::write(path, &md)
        .with_context(|| format!("Failed to write Markdown wiki to {:?}", path))?;

    info!("Wrote wiki page to {} ({} categories)", path, grouped.len());
    Ok(())
}

/// Simple capitalise helper for category headings.
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extractor::ExtractedFact;
    use chrono::NaiveDate;

    fn sample_facts() -> Vec<ExtractedFact> {
        vec![
            ExtractedFact {
                category: "preference".into(),
                content: "loves dark mode".into(),
                source_file: "memory/2026-05-10.md".into(),
                line_number: 12,
                date: Some(NaiveDate::from_ymd_opt(2026, 5, 10).unwrap()),
                confidence: 0.95,
            },
            ExtractedFact {
                category: "todo".into(),
                content: "finish extraction crate".into(),
                source_file: "memory/2026-05-15.md".into(),
                line_number: 3,
                date: Some(NaiveDate::from_ymd_opt(2026, 5, 15).unwrap()),
                confidence: 0.85,
            },
        ]
    }

    #[tokio::test]
    async fn test_jsonl_roundtrip() -> Result<()> {
        let tmp = std::env::temp_dir().join("soulsystem-test-jsonl.jsonl");
        let path = tmp.to_str().unwrap().to_string();
        persist_jsonl(&sample_facts(), &path)?;

        let content = fs::read_to_string(&path)?;
        assert!(content.contains("preference"));
        assert!(content.contains("loves dark mode"));

        fs::remove_file(&path)?;
        Ok(())
    }

    #[tokio::test]
    async fn test_markdown_output() -> Result<()> {
        let tmp = std::env::temp_dir().join("soulsystem-test-wiki.md");
        let path = tmp.to_str().unwrap().to_string();
        persist_markdown(&sample_facts(), &path)?;

        let content = fs::read_to_string(&path)?;
        assert!(content.contains("## Preference"));
        assert!(content.contains("## Todo"));
        assert!(content.contains("loves dark mode"));
        assert!(content.contains("finish extraction crate"));

        fs::remove_file(&path)?;
        Ok(())
    }

    #[test]
    fn test_capitalize() {
        assert_eq!(capitalize("preference"), "Preference");
        assert_eq!(capitalize(""), "");
        assert_eq!(capitalize("hello world"), "Hello world");
    }
}
